//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.01 at 11:38:05 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nesterova.com/springeshop/ws/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nesterova.springeshop.ws.products;
